services:

  authentication:
    build: ./authentication
    ports:
      - "5001:5001"
    volumes:
      - ./authentication:/app
    environment:
      FLASK_APP: server.py
      FLASK_ENV: development
      TAIGA_URL: https://api.taiga.io/api/v1
  
  cfd:
    build: ./cfd
    ports:
      - "5004:5004"
    volumes:
      - ./cfd:/app
    environment:
      FLASK_APP: server.py
      FLASK_ENV: development
      TAIGA_URL: https://api.taiga.io/api/v1
  
  cycletime:
    build: ./cycletime
    ports:
      - "5002:5002"
    volumes:
      - ./cycletime:/app
    environment:
      FLASK_APP: server.py
      FLASK_ENV: development
      TAIGA_URL: https://api.taiga.io/api/v1

  leadtime:
    build: ./leadTime
    ports:
      - "5003:5003"
    volumes:
      - ./leadtime:/app
    environment:
      FLASK_APP: server.py
      FLASK_ENV: development
      TAIGA_URL: https://api.taiga.io/api/v1

  throughput:
    build: ./throughput
    ports:
      - "5005:5005"
    volumes:
      - ./throughput:/app
    environment:
      FLASK_APP: server.py
      FLASK_ENV: development
      TAIGA_URL: https://api.taiga.io/api/v1

  apigateway:
    build: ./apigateway
    ports:
     - "5050:5050"
    volumes:
      - ./apigateway:/app
    environment:
      FLASK_APP: server.py
      FLASK_ENV: development
      TAIGA_URL: https://api.taiga.io/api/v1
      AUTH_URL: http://authentication:5001
      CYCLETIME_URL: http://cycletime:5002
      LEADTIME_URL: http://leadtime:5003
      THROUGHPUT_URL: http://throughput:5005
      CFD_URL: http://cfd:5004

  frontend:
    build:
      context: ./ui
    ports:
      - "3000:3000"
    volumes:
      - ./ui:/app
      - /app/node_modules
    environment:
      REACT_APP_BACKEND_URI: http://localhost:5050/
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: 'true' # Helps with hot-reloading in Docker