data = [
    {
        "due_date": None,
        "due_date_reason": "",
        "due_date_status": "not_set",
        "total_comments": 0,
        "tags": [],
        "attachments": [],
        "status": 9182125,
        "status_extra_info": {
            "name": "New",
            "color": "#70728F",
            "is_closed": False
        },
        "assigned_to": None,
        "assigned_to_extra_info": None,
        "owner": 618761,
        "owner_extra_info": {
            "username": "avijay48",
            "full_name_display": "Akash Vijayasarathy",
            "photo": None,
            "big_photo": None,
            "gravatar_id": "30ab79a1ca24196d19f471e441d91304",
            "is_active": True,
            "id": 618761
        },
        "is_watcher": False,
        "total_watchers": 0,
        "is_voter": False,
        "total_voters": 0,
        "project": 1525740,
        "project_extra_info": {
            "name": "Taiga Metrics Tool Testing Project (Team-Houston)",
            "slug": "rnolas96-taiga-metrics-tool-testing-project-team-houston",
            "logo_small_url": None,
            "id": 1525740
        },
        "id": 5493380,
        "ref": 1,
        "milestone": 378136,
        "milestone_slug": "sprint1-1059",
        "milestone_name": "sprint1",
        "is_closed": True,
        "points": {
            "9209165": 18344164
        },
        "backlog_order": 1707695375801041,
        "sprint_order": 1,
        "kanban_order": 1707695375824504,
        "created_date": "2024-02-11T23:49:35.824Z",
        "modified_date": "2024-02-11T23:49:35.836Z",
        "finish_date": "2024-02-11T23:52:30.626Z",
        "subject": "userstory1",
        "client_requirement": False,
        "team_requirement": False,
        "generated_from_issue": None,
        "generated_from_task": None,
        "from_task_ref": None,
        "external_reference": None,
        "tribe_gig": None,
        "version": 1,
        "watchers": [],
        "is_blocked": False,
        "blocked_note": "",
        "total_points": None,
        "comment": "",
        "origin_issue": None,
        "origin_task": None,
        "epics": None,
        "epic_order": None,
        "tasks": [],
        "total_attachments": 0,
        "swimlane": None,
        "assigned_users": []
    },
    {
        "due_date": None,
        "due_date_reason": "",
        "due_date_status": "not_set",
        "total_comments": 0,
        "tags": [],
        "attachments": [],
        "status": 9182125,
        "status_extra_info": {
            "name": "New",
            "color": "#70728F",
            "is_closed": False
        },
        "assigned_to": None,
        "assigned_to_extra_info": None,
        "owner": 618761,
        "owner_extra_info": {
            "username": "avijay48",
            "full_name_display": "Akash Vijayasarathy",
            "photo": None,
            "big_photo": None,
            "gravatar_id": "30ab79a1ca24196d19f471e441d91304",
            "is_active": True,
            "id": 618761
        },
        "is_watcher": False,
        "total_watchers": 0,
        "is_voter": False,
        "total_voters": 0,
        "project": 1525740,
        "project_extra_info": {
            "name": "Taiga Metrics Tool Testing Project (Team-Houston)",
            "slug": "rnolas96-taiga-metrics-tool-testing-project-team-houston",
            "logo_small_url": None,
            "id": 1525740
        },
        "id": 5493381,
        "ref": 3,
        "milestone": 378137,
        "milestone_slug": "scrum2",
        "milestone_name": "sprint2",
        "is_closed": True,
        "points": {
            "9209165": 18344164
        },
        "backlog_order": 1707695514417415,
        "sprint_order": 1,
        "kanban_order": 1707695514440637,
        "created_date": "2024-02-11T23:51:54.440Z",
        "modified_date": "2024-02-11T23:51:54.452Z",
        "finish_date": "2024-02-11T23:52:22.749Z",
        "subject": "userstory2",
        "client_requirement": False,
        "team_requirement": False,
        "generated_from_issue": None,
        "generated_from_task": None,
        "from_task_ref": None,
        "external_reference": None,
        "tribe_gig": None,
        "version": 1,
        "watchers": [],
        "is_blocked": False,
        "blocked_note": "",
        "total_points": None,
        "comment": "",
        "origin_issue": None,
        "origin_task": None,
        "epics": None,
        "epic_order": None,
        "tasks": [],
        "total_attachments": 0,
        "swimlane": None,
        "assigned_users": []
    },
    {
        "due_date": None,
        "due_date_reason": "",
        "due_date_status": "not_set",
        "total_comments": 0,
        "tags": [],
        "attachments": [],
        "status": 9182125,
        "status_extra_info": {
            "name": "New",
            "color": "#70728F",
            "is_closed": False
        },
        "assigned_to": None,
        "assigned_to_extra_info": None,
        "owner": 618761,
        "owner_extra_info": {
            "username": "avijay48",
            "full_name_display": "Akash Vijayasarathy",
            "photo": None,
            "big_photo": None,
            "gravatar_id": "30ab79a1ca24196d19f471e441d91304",
            "is_active": True,
            "id": 618761
        },
        "is_watcher": False,
        "total_watchers": 0,
        "is_voter": False,
        "total_voters": 0,
        "project": 1525740,
        "project_extra_info": {
            "name": "Taiga Metrics Tool Testing Project (Team-Houston)",
            "slug": "rnolas96-taiga-metrics-tool-testing-project-team-houston",
            "logo_small_url": None,
            "id": 1525740
        },
        "id": 5493384,
        "ref": 5,
        "milestone": 378138,
        "milestone_slug": "sprint3-634",
        "milestone_name": "sprint3",
        "is_closed": False,
        "points": {
            "9209165": 18344173
        },
        "backlog_order": 1707696279417306,
        "sprint_order": 1,
        "kanban_order": 1707696279440939,
        "created_date": "2024-02-12T00:04:39.440Z",
        "modified_date": "2024-02-27T23:38:17.133Z",
        "finish_date": None,
        "subject": "userstory2",
        "client_requirement": False,
        "team_requirement": False,
        "generated_from_issue": None,
        "generated_from_task": None,
        "from_task_ref": None,
        "external_reference": None,
        "tribe_gig": None,
        "version": 2,
        "watchers": [],
        "is_blocked": False,
        "blocked_note": "",
        "total_points": 13.0,
        "comment": "",
        "origin_issue": None,
        "origin_task": None,
        "epics": None,
        "epic_order": None,
        "tasks": [],
        "total_attachments": 0,
        "swimlane": None,
        "assigned_users": []
    },
    {
        "due_date": None,
        "due_date_reason": "",
        "due_date_status": "not_set",
        "total_comments": 0,
        "tags": [],
        "attachments": [],
        "status": 9182125,
        "status_extra_info": {
            "name": "New",
            "color": "#70728F",
            "is_closed": False
        },
        "assigned_to": None,
        "assigned_to_extra_info": None,
        "owner": 618761,
        "owner_extra_info": {
            "username": "avijay48",
            "full_name_display": "Akash Vijayasarathy",
            "photo": None,
            "big_photo": None,
            "gravatar_id": "30ab79a1ca24196d19f471e441d91304",
            "is_active": True,
            "id": 618761
        },
        "is_watcher": False,
        "total_watchers": 0,
        "is_voter": False,
        "total_voters": 0,
        "project": 1525740,
        "project_extra_info": {
            "name": "Taiga Metrics Tool Testing Project (Team-Houston)",
            "slug": "rnolas96-taiga-metrics-tool-testing-project-team-houston",
            "logo_small_url": None,
            "id": 1525740
        },
        "id": 5523891,
        "ref": 7,
        "milestone": 378138,
        "milestone_slug": "sprint3-634",
        "milestone_name": "sprint3",
        "is_closed": False,
        "points": {
            "9209165": 18344171
        },
        "backlog_order": 1708998729999302,
        "sprint_order": 2,
        "kanban_order": 1708998730021187,
        "created_date": "2024-02-27T01:52:10.021Z",
        "modified_date": "2024-02-27T13:55:23.758Z",
        "finish_date": None,
        "subject": "fetchdetails",
        "client_requirement": False,
        "team_requirement": False,
        "generated_from_issue": None,
        "generated_from_task": None,
        "from_task_ref": None,
        "external_reference": None,
        "tribe_gig": None,
        "version": 3,
        "watchers": [],
        "is_blocked": False,
        "blocked_note": "",
        "total_points": 8.0,
        "comment": "",
        "origin_issue": None,
        "origin_task": None,
        "epics": None,
        "epic_order": None,
        "tasks": [],
        "total_attachments": 0,
        "swimlane": None,
        "assigned_users": []
    },
    {
        "due_date": None,
        "due_date_reason": "",
        "due_date_status": "not_set",
        "total_comments": 0,
        "tags": [],
        "attachments": [],
        "status": 9182125,
        "status_extra_info": {
            "name": "New",
            "color": "#70728F",
            "is_closed": False
        },
        "assigned_to": None,
        "assigned_to_extra_info": None,
        "owner": 618761,
        "owner_extra_info": {
            "username": "avijay48",
            "full_name_display": "Akash Vijayasarathy",
            "photo": None,
            "big_photo": None,
            "gravatar_id": "30ab79a1ca24196d19f471e441d91304",
            "is_active": True,
            "id": 618761
        },
        "is_watcher": False,
        "total_watchers": 0,
        "is_voter": False,
        "total_voters": 0,
        "project": 1525740,
        "project_extra_info": {
            "name": "Taiga Metrics Tool Testing Project (Team-Houston)",
            "slug": "rnolas96-taiga-metrics-tool-testing-project-team-houston",
            "logo_small_url": None,
            "id": 1525740
        },
        "id": 5523894,
        "ref": 8,
        "milestone": None,
        "milestone_slug": None,
        "milestone_name": None,
        "is_closed": False,
        "points": {
            "9209165": 18344164
        },
        "backlog_order": 1708999337066625,
        "sprint_order": 1708999337066650,
        "kanban_order": 1708999337088809,
        "created_date": "2024-02-27T02:02:17.088Z",
        "modified_date": "2024-02-27T02:02:17.100Z",
        "finish_date": None,
        "subject": "visualize",
        "client_requirement": False,
        "team_requirement": False,
        "generated_from_issue": None,
        "generated_from_task": None,
        "from_task_ref": None,
        "external_reference": None,
        "tribe_gig": None,
        "version": 1,
        "watchers": [],
        "is_blocked": False,
        "blocked_note": "",
        "total_points": None,
        "comment": "",
        "origin_issue": None,
        "origin_task": None,
        "epics": None,
        "epic_order": None,
        "tasks": [],
        "total_attachments": 0,
        "swimlane": None,
        "assigned_users": []
    }
]