name: Build and publish Docker Image Using Docker Compose

on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the repository
              uses: actions/checkout@v2

            - name: Build the Docker images
              run: docker compose build
            
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_TOKEN }}
            
            - name: Push the Docker images
              run: docker compose push

            - name: Remote SSH to the server
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{ secrets.HOST_IP }}
                username: ${{ secrets.HOST_USERNAME }}
                key: ${{ secrets.SSH_KEY }}
                script: whoami
                  
            # - name: Tag Docker image
            #   run: docker tag ser516-team-atlhou:latest ishtpreet/ser516-team-atlhou:latest
    
            # - name: Push Docker image to Docker Hub
            #   run: docker push ishtpreet/ser516-team-atlhou:latest
            