name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './ui/package-lock.json'
      - name: Generate package-lock.json in sync with the node version
        run: cd ./ui && npm install --package-lock-only
      - name: Install
        run: cd ./ui && npm ci --prefer-offline
      - name: Eslint
        run: cd ./ui && npm run eslint -- --max-warnings 0
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install Flake8
        run: pip install flake8
      - name: Run Flake8
        run: cd ./taigaProject && flake8 .
